# Generated by Django 2.2.5 on 2019-10-15 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='storedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_city', models.CharField(max_length=250)),
                ('store_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.store')),
            ],
        ),
        migrations.CreateModel(
            name='marchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_marchandise', models.CharField(max_length=250, unique=True)),
                ('store_address', models.CharField(max_length=250)),
                ('store_contact_no', models.CharField(max_length=12)),
                ('store_lat', models.CharField(max_length=12)),
                ('store_lng', models.CharField(max_length=12)),
                ('store_available', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.storedata')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.store')),
            ],
        ),
    ]
